name: Deploy # The name of the workflow
on: 
  push:
    branches:
      - main #Launch the action on every push on the branch main
jobs:
  build:
    runs-on: ubuntu-latest # Setup an environment to run the action
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - uses: akhileshns/heroku-deploy@v3.12.12 # This action deploys the content on Heroku
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}} #The Heroku api key we stored on our repo secret
          heroku_app_name: "jobpal-test" #The name of your heroku app - Must be unique in Heroku
          heroku_email: "aa0903765@gmail.com" #Your heroku yuser name
          branch: main